version: "3.7"

services:
  goaccess:
    image: https://github.com/owlabout/dockerfiles.git#:goaccess
    environment:
      - API_KEY
      - DOMAIN
      - RECIPIENT
    volumes:
      - /var/log/traefik/access.log:/access.log
    container_name: goaccess
